
import json
import os

import shapely.geometry
import shapely.ops

from terraforge.utils.coordinates import CoordinateConverter
from terraforge.utils.logging import logger

DEFAULT_BUILDING_HEIGHT = 10.0


def _sanitize(name):
    return str(name).replace(':', '_').replace('/', '_').replace(' ', '_')


def _write_model_config(model_dir, model_name):
    config_path = os.path.join(model_dir, 'model.config')
    with open(config_path, 'w') as f:
        f.write(f"""<?xml version='1.0'?>
<model>
  <name>{model_name}</name>
  <version>1.0</version>
  <sdf version='1.10'>model.sdf</sdf>
  <description>Generated by TerraForge.</description>
</model>
""")


def process_osm_buildings_to_sdf(osm_filepath: str, models_dir: str, origin_wgs84: tuple):
    """
    Process OSM building footprints from a GeoJSON file and write one Gazebo
    model per building under ``models_dir`` using the standard
    ``<models_dir>/<model_name>/{model.sdf,model.config}`` layout. Geometry is
    expressed in the local Gazebo frame whose origin is ``origin_wgs84``
    (lat, lon).

    Returns a list of ``{'model_name': str, 'pose_xy': (x, y)}`` dicts — one
    per generated building — so callers can emit ``model://<name>`` includes.
    """
    logger.info(f"Processing OSM buildings from {osm_filepath} to models in {models_dir}")
    os.makedirs(models_dir, exist_ok=True)

    converter = CoordinateConverter(origin_wgs84)

    def project(x_lon, y_lat, z=None):
        gx, gy, _ = converter.wgs84_to_gazebo((y_lat, x_lon))
        return (gx, gy) if z is None else (gx, gy, z)

    buildings = []
    try:
        with open(osm_filepath, 'r') as f:
            osm_data = json.load(f)

        for feature_idx, feature in enumerate(osm_data['features']):
            geom_type = feature['geometry']['type']
            if geom_type not in ('Polygon', 'MultiPolygon'):
                logger.warning(
                    f"Feature {feature_idx} is {geom_type}, not a building polygon. Skipping."
                )
                continue

            props = feature['properties']
            building_id = props.get('osmid', f"{feature_idx}")
            height = float(props.get('height', DEFAULT_BUILDING_HEIGHT))

            polygon_wgs84 = shapely.geometry.shape(feature['geometry'])
            polygon_local = shapely.ops.transform(project, polygon_wgs84)

            minx, miny, maxx, maxy = polygon_local.bounds
            size_x = max(maxx - minx, 0.1)
            size_y = max(maxy - miny, 0.1)
            size_z = height

            centroid_local = polygon_local.centroid
            pose_xy = (centroid_local.x, centroid_local.y)

            model_name = f"building_{_sanitize(building_id)}_{feature_idx}"
            model_dir = os.path.join(models_dir, model_name)
            os.makedirs(model_dir, exist_ok=True)

            sdf_content = f"""<?xml version='1.0'?>
<sdf version='1.10'>
  <model name='{model_name}'>
    <static>true</static>
    <pose>0 0 {size_z / 2.0} 0 0 0</pose>
    <link name='link'>
      <collision name='collision'>
        <geometry>
          <box>
            <size>{size_x} {size_y} {size_z}</size>
          </box>
        </geometry>
      </collision>
      <visual name='visual'>
        <geometry>
          <box>
            <size>{size_x} {size_y} {size_z}</size>
          </box>
        </geometry>
        <material>
          <ambient>0.7 0.7 0.7 1</ambient>
          <diffuse>0.7 0.7 0.7 1</diffuse>
          <specular>0.1 0.1 0.1 1</specular>
          <emissive>0 0 0 1</emissive>
        </material>
      </visual>
    </link>
  </model>
</sdf>
"""
            with open(os.path.join(model_dir, 'model.sdf'), 'w') as f:
                f.write(sdf_content)
            _write_model_config(model_dir, model_name)

            buildings.append({'model_name': model_name, 'pose_xy': pose_xy})
            logger.debug(f"Generated model {model_name} in {model_dir}")

        logger.info(f"OSM buildings processed: {len(buildings)} models in {models_dir}")
        return buildings
    except Exception as e:
        logger.error(f"Error processing OSM buildings to SDF models: {e}")
        raise
