"""Turn OSM ``highway=*`` LineStrings into Gazebo road models.

Each OSM way becomes one static model. The way's polyline is buffered by its
per-class width (motorway wider than residential) and emitted as an extruded
SDF ``<polyline>`` polygon with a small thickness so it sits just above the
terrain. Elevations are sampled along the way and averaged to keep the road
roughly flush with the ground.
"""

import json
import math
import os

import shapely.affinity
import shapely.geometry
import shapely.ops

from terraforge.utils.coordinates import CoordinateConverter
from terraforge.utils.logging import logger

# Per-highway-class half-width (meters). Road total width = 2 * entry.
_ROAD_HALF_WIDTH = {
    'motorway':    7.5,
    'trunk':       6.0,
    'primary':     5.0,
    'secondary':   4.0,
    'tertiary':    3.5,
    'residential': 3.0,
    'service':     2.5,
    'unclassified': 3.0,
    'track':       2.0,
    'path':        1.0,
    'footway':     0.8,
    'cycleway':    1.0,
}
_DEFAULT_HALF_WIDTH = 2.5
ROAD_THICKNESS = 0.08  # meters above terrain
ROAD_COLOR = (0.20, 0.20, 0.22)  # dark asphalt


def _half_width(props: dict) -> float:
    hw = _ROAD_HALF_WIDTH.get(str(props.get('highway', '')).lower(), _DEFAULT_HALF_WIDTH)
    # OSM-declared <width> overrides per-class default.
    if 'width' in props:
        try:
            return max(float(str(props['width']).rstrip(' m')) / 2.0, 0.5)
        except (TypeError, ValueError):
            pass
    return hw


def _sanitize(name):
    return str(name).replace(':', '_').replace('/', '_').replace(' ', '_')


def _write_model_config(model_dir, model_name):
    with open(os.path.join(model_dir, 'model.config'), 'w') as f:
        f.write(f"""<?xml version='1.0'?>
<model>
  <name>{model_name}</name>
  <version>1.0</version>
  <sdf version='1.10'>model.sdf</sdf>
  <description>Generated by TerraForge.</description>
</model>
""")


def _polygon_to_polyline_sdf(polygon, thickness, color=ROAD_COLOR) -> str:
    """Visual-only extruded polygon. Roads are ~8cm slabs — no collision needed;
    the rover drives over them. Avoids dartsim polyline-collision failures."""
    if polygon.geom_type != 'Polygon' or not polygon.is_valid or not polygon.is_simple:
        return None
    if not polygon.exterior.is_ccw:
        polygon = shapely.geometry.polygon.orient(polygon, sign=1.0)
    coords = list(polygon.exterior.coords)
    if coords[0] == coords[-1]:
        coords = coords[:-1]
    pts = "\n            ".join(f"<point>{x:.3f} {y:.3f}</point>" for x, y in coords)
    r, g, b = color
    return f"""    <static>true</static>
    <link name='link'>
      <visual name='visual'>
        <geometry>
          <polyline>
            {pts}
            <height>{thickness:.3f}</height>
          </polyline>
        </geometry>
        <material>
          <ambient>{r} {g} {b} 1</ambient>
          <diffuse>{r} {g} {b} 1</diffuse>
          <specular>0.05 0.05 0.05 1</specular>
        </material>
      </visual>
    </link>"""


def process_osm_roads_to_sdf(osm_filepath: str, models_dir: str, origin_wgs84: tuple,
                             elevation_sampler=None) -> list:
    """Return a list of ``{model_name, pose_xy, pose_z}`` road placements.

    Each LineString becomes one buffered polygon-extrusion model. Non-line
    geometries in the GeoJSON (e.g. crossing markers) are skipped.
    """
    if not os.path.exists(osm_filepath):
        logger.info("No OSM roads file; skipping roads stage.")
        return []

    logger.info(f"Processing OSM roads from {osm_filepath} to models in {models_dir}")
    os.makedirs(models_dir, exist_ok=True)

    converter = CoordinateConverter(origin_wgs84)

    def project(x_lon, y_lat, z=None):
        gx, gy, _ = converter.wgs84_to_gazebo((y_lat, x_lon))
        return (gx, gy) if z is None else (gx, gy, z)

    placements = []
    skipped = 0
    with open(osm_filepath) as f:
        osm_data = json.load(f)

    for feature_idx, feature in enumerate(osm_data['features']):
        geom = feature.get('geometry', {})
        gtype = geom.get('type')
        props = feature.get('properties', {}) or {}
        if gtype not in ('LineString', 'MultiLineString'):
            skipped += 1
            continue

        line_wgs84 = shapely.geometry.shape(geom)
        line_local = shapely.ops.transform(project, line_wgs84)
        if line_local.is_empty or line_local.length < 0.5:
            skipped += 1
            continue

        half_w = _half_width(props)
        # Buffer the line to a polygon (flat road surface). cap_style=2 → flat
        # ends, join_style=2 → mitered joints → no weird rounded blobs.
        try:
            poly_local = line_local.buffer(half_w, cap_style=2, join_style=2)
        except Exception:
            skipped += 1
            continue
        if poly_local.is_empty or poly_local.geom_type != 'Polygon':
            skipped += 1
            continue

        centroid = poly_local.centroid
        pose_xy = (centroid.x, centroid.y)
        poly_centered = shapely.affinity.translate(
            poly_local, xoff=-pose_xy[0], yoff=-pose_xy[1]
        )

        # Average terrain height along the line so the road approximately
        # follows ground elevation (still flat per-segment; dartsim won't
        # collide against the heightmap anyway).
        if elevation_sampler is not None:
            samples = []
            length = line_local.length
            n = max(int(length / 20), 2)
            for i in range(n + 1):
                p = line_local.interpolate(i / n, normalized=True)
                samples.append(elevation_sampler(p.x, p.y))
            pose_z = sum(samples) / len(samples) + ROAD_THICKNESS / 2.0
        else:
            pose_z = ROAD_THICKNESS / 2.0

        road_id = props.get('osmid', f"{feature_idx}")
        model_name = f"road_{_sanitize(road_id)}_{feature_idx}"

        body_sdf = _polygon_to_polyline_sdf(poly_centered, ROAD_THICKNESS)
        if body_sdf is None:
            skipped += 1
            continue

        model_dir = os.path.join(models_dir, model_name)
        os.makedirs(model_dir, exist_ok=True)
        sdf_content = f"""<?xml version='1.0'?>
<sdf version='1.10'>
  <model name='{model_name}'>
{body_sdf}
  </model>
</sdf>
"""
        with open(os.path.join(model_dir, 'model.sdf'), 'w') as f:
            f.write(sdf_content)
        _write_model_config(model_dir, model_name)

        placements.append({'model_name': model_name, 'pose_xy': pose_xy, 'pose_z': pose_z})

    logger.info(f"OSM roads processed: {len(placements)} road models, {skipped} skipped")
    return placements
