"""Turn OSM ``highway=*`` LineStrings into Gazebo road models.

Each OSM way becomes one static model. The way's polyline is buffered by its
per-class width (motorway wider than residential) and emitted as an extruded
SDF ``<polyline>`` polygon with a small thickness so it sits just above the
terrain. Elevations are sampled along the way and averaged to keep the road
roughly flush with the ground.
"""

import json
import math
import os

import shapely.affinity
import shapely.geometry
import shapely.ops

from terraforge.utils.coordinates import CoordinateConverter
from terraforge.utils.logging import logger

# Per-highway-class half-width (meters). Road total width = 2 * entry.
_ROAD_HALF_WIDTH = {
    'motorway':    7.5,
    'trunk':       6.0,
    'primary':     5.0,
    'secondary':   4.0,
    'tertiary':    3.5,
    'residential': 3.0,
    'service':     2.5,
    'unclassified': 3.0,
    'track':       2.0,
    'path':        1.0,
    'footway':     0.8,
    'cycleway':    1.0,
}
_DEFAULT_HALF_WIDTH = 2.5
ROAD_THICKNESS = 0.08  # meters above terrain
ROAD_COLOR = (0.20, 0.20, 0.22)  # dark asphalt

# Max length (meters) of a single road segment before the emitter breaks
# the OSM way into multiple sub-segments. Each sub-segment gets its own
# elevation sample and its own flat slab, so the chain of slabs follows
# the DEM at segment granularity instead of one giant horizontal plank.
# 20 m is short enough to stay close to the terrain even on steep
# hillsides (~5 deg per 20 m = ~1.8 m drop, below ROAD_THICKNESS +
# visible z-fight margin) without multiplying output SDF size too much.
_ROAD_SEGMENT_MAX_LEN_M = 20.0


def _half_width(props: dict) -> float:
    hw = _ROAD_HALF_WIDTH.get(str(props.get('highway', '')).lower(), _DEFAULT_HALF_WIDTH)
    # OSM-declared <width> overrides per-class default.
    if 'width' in props:
        try:
            return max(float(str(props['width']).rstrip(' m')) / 2.0, 0.5)
        except (TypeError, ValueError):
            pass
    return hw


def _sanitize(name):
    return str(name).replace(':', '_').replace('/', '_').replace(' ', '_')


def _write_model_config(model_dir, model_name):
    with open(os.path.join(model_dir, 'model.config'), 'w') as f:
        f.write(f"""<?xml version='1.0'?>
<model>
  <name>{model_name}</name>
  <version>1.0</version>
  <sdf version='1.10'>model.sdf</sdf>
  <description>Generated by TerraForge.</description>
</model>
""")


def _polygon_to_polyline_sdf(polygon, thickness, color=ROAD_COLOR) -> str:
    """Visual-only extruded polygon. Roads are ~8cm slabs — no collision needed;
    the rover drives over them. Avoids dartsim polyline-collision failures."""
    if polygon.geom_type != 'Polygon' or not polygon.is_valid or not polygon.is_simple:
        return None
    if not polygon.exterior.is_ccw:
        polygon = shapely.geometry.polygon.orient(polygon, sign=1.0)
    coords = list(polygon.exterior.coords)
    if coords[0] == coords[-1]:
        coords = coords[:-1]
    pts = "\n            ".join(f"<point>{x:.3f} {y:.3f}</point>" for x, y in coords)
    r, g, b = color
    return f"""    <static>true</static>
    <link name='link'>
      <visual name='visual'>
        <geometry>
          <polyline>
            {pts}
            <height>{thickness:.3f}</height>
          </polyline>
        </geometry>
        <material>
          <ambient>{r} {g} {b} 1</ambient>
          <diffuse>{r} {g} {b} 1</diffuse>
          <specular>0.05 0.05 0.05 1</specular>
        </material>
      </visual>
    </link>"""


def process_osm_roads_to_sdf(osm_filepath: str, models_dir: str, origin_wgs84: tuple,
                             elevation_sampler=None) -> list:
    """Return a list of ``{model_name, pose_xy, pose_z}`` road placements.

    Each LineString becomes one buffered polygon-extrusion model. Non-line
    geometries in the GeoJSON (e.g. crossing markers) are skipped.
    """
    if not os.path.exists(osm_filepath):
        logger.info("No OSM roads file; skipping roads stage.")
        return []

    logger.info(f"Processing OSM roads from {osm_filepath} to models in {models_dir}")
    os.makedirs(models_dir, exist_ok=True)

    converter = CoordinateConverter(origin_wgs84)

    def project(x_lon, y_lat, z=None):
        gx, gy, _ = converter.wgs84_to_gazebo((y_lat, x_lon))
        return (gx, gy) if z is None else (gx, gy, z)

    placements = []
    skipped = 0
    with open(osm_filepath) as f:
        osm_data = json.load(f)

    for feature_idx, feature in enumerate(osm_data['features']):
        geom = feature.get('geometry', {})
        gtype = geom.get('type')
        props = feature.get('properties', {}) or {}
        if gtype not in ('LineString', 'MultiLineString'):
            skipped += 1
            continue

        line_wgs84 = shapely.geometry.shape(geom)
        line_local = shapely.ops.transform(project, line_wgs84)
        if line_local.is_empty or line_local.length < 0.5:
            skipped += 1
            continue

        half_w = _half_width(props)
        road_id = props.get('osmid', f"{feature_idx}")
        base_name = f"road_{_sanitize(road_id)}_{feature_idx}"

        # MultiLineString: iterate component lines; each becomes its own
        # segment chain below.
        if line_local.geom_type == 'MultiLineString':
            component_lines = list(line_local.geoms)
        else:
            component_lines = [line_local]

        for comp_idx, comp_line in enumerate(component_lines):
            emitted = _emit_road_segments(
                comp_line, half_w, base_name, comp_idx, models_dir,
                elevation_sampler=elevation_sampler,
            )
            if emitted == 0:
                skipped += 1
            else:
                placements.extend(_segment_placements)
                _segment_placements.clear()

    logger.info(f"OSM roads processed: {len(placements)} road models, {skipped} skipped")
    return placements


# Module-level buffer used by _emit_road_segments as a simple return
# channel (keeps the per-segment emit function self-contained without
# growing its signature). Cleared by the caller after each component.
_segment_placements = []


def _emit_road_segments(line_local, half_w, base_name, comp_idx, models_dir,
                        elevation_sampler=None):
    """Break ``line_local`` into chunks of <= _ROAD_SEGMENT_MAX_LEN_M and
    emit one flat-slab model per chunk, sampling elevation at each chunk's
    midpoint so the sequence of slabs follows the DEM instead of producing
    one long horizontal plank.
    """
    length = line_local.length
    if length < 0.5:
        return 0

    n_segments = max(1, int(math.ceil(length / _ROAD_SEGMENT_MAX_LEN_M)))
    emitted = 0
    for seg_idx in range(n_segments):
        t0 = seg_idx / n_segments
        t1 = (seg_idx + 1) / n_segments
        # Walk the parametric LineString into a list of vertices covering
        # [t0, t1], keeping any original OSM vertices that fall inside so
        # curvature isn't lost to coarse resampling.
        seg_pts = _subline_points(line_local, t0, t1)
        if len(seg_pts) < 2:
            continue
        seg_line = shapely.geometry.LineString(seg_pts)
        try:
            poly_local = seg_line.buffer(half_w, cap_style=2, join_style=2)
        except Exception:
            continue
        if poly_local.is_empty or poly_local.geom_type != 'Polygon':
            continue

        centroid = poly_local.centroid
        pose_xy = (centroid.x, centroid.y)
        poly_centered = shapely.affinity.translate(
            poly_local, xoff=-pose_xy[0], yoff=-pose_xy[1]
        )

        if elevation_sampler is not None:
            # Sample endpoints + midpoint of the sub-segment — enough for a
            # good average on a short chunk, cheap with a cached sampler.
            mid = seg_line.interpolate(0.5, normalized=True)
            start = seg_pts[0]
            end = seg_pts[-1]
            samples = [
                elevation_sampler(start[0], start[1]),
                elevation_sampler(mid.x, mid.y),
                elevation_sampler(end[0], end[1]),
            ]
            pose_z = sum(samples) / len(samples) + ROAD_THICKNESS / 2.0
        else:
            pose_z = ROAD_THICKNESS / 2.0

        model_name = f"{base_name}_c{comp_idx}_s{seg_idx}"
        body_sdf = _polygon_to_polyline_sdf(poly_centered, ROAD_THICKNESS)
        if body_sdf is None:
            continue

        model_dir = os.path.join(models_dir, model_name)
        os.makedirs(model_dir, exist_ok=True)
        sdf_content = f"""<?xml version='1.0'?>
<sdf version='1.10'>
  <model name='{model_name}'>
{body_sdf}
  </model>
</sdf>
"""
        with open(os.path.join(model_dir, 'model.sdf'), 'w') as f:
            f.write(sdf_content)
        _write_model_config(model_dir, model_name)

        _segment_placements.append({
            'model_name': model_name,
            'pose_xy': pose_xy,
            'pose_z': pose_z,
        })
        emitted += 1
    return emitted


def _subline_points(line, t0, t1):
    """Return the vertex sequence of ``line`` restricted to the parametric
    range [t0, t1] (normalized), keeping any original OSM vertices that
    fall strictly inside so the sub-line preserves curvature.
    """
    pts = [line.interpolate(t0, normalized=True)]
    total = line.length
    if total <= 0:
        return [(pts[0].x, pts[0].y)]
    target_lo = t0 * total
    target_hi = t1 * total
    # Walk the original vertices; distance-along-line is monotonic.
    coords = list(line.coords)
    if len(coords) < 2:
        return [(coords[0][0], coords[0][1])]
    accumulated = 0.0
    for i in range(1, len(coords)):
        x0, y0 = coords[i - 1][0], coords[i - 1][1]
        x1, y1 = coords[i][0], coords[i][1]
        seg_len = math.hypot(x1 - x0, y1 - y0)
        next_acc = accumulated + seg_len
        if next_acc > target_lo and accumulated < target_hi:
            # This original segment overlaps [target_lo, target_hi].
            if accumulated >= target_lo and accumulated <= target_hi:
                pts.append(shapely.geometry.Point(x0, y0))
        accumulated = next_acc
        if accumulated >= target_hi:
            break
    pts.append(line.interpolate(t1, normalized=True))
    return [(p.x, p.y) for p in pts]
