"""Turn OSM ``natural=tree`` points and ``natural=wood`` / ``landuse=forest``
polygons into Gazebo tree instances.

Each tree is a single static model (trunk cylinder + canopy sphere). We emit
one reusable ``tree_generic_<variant>`` model and place many ``<include>``
instances in the world — avoiding thousands of per-instance SDF files.
"""

import json
import os
import random

import shapely.affinity
import shapely.geometry
import shapely.ops

from terraforge.utils.coordinates import CoordinateConverter
from terraforge.utils.logging import logger

# Number of reusable tree variants (different heights / canopy radii) that
# will be generated once and referenced by each placement.
TREE_VARIANTS = 5
# Target density for forest-polygon scatter (trees per square meter).
FOREST_DENSITY = 1 / 400.0
# Hard cap on scattered trees per world to keep Gazebo sane. gz-transport v13
# has a thread-safety bug around getenv() that segfaults the GUI when scene
# updates fire too fast during load; keeping total instances modest helps.
MAX_FOREST_TREES = 200


def _write_model_config(model_dir, model_name):
    with open(os.path.join(model_dir, 'model.config'), 'w') as f:
        f.write(f"""<?xml version='1.0'?>
<model>
  <name>{model_name}</name>
  <version>1.0</version>
  <sdf version='1.10'>model.sdf</sdf>
  <description>Generated by TerraForge.</description>
</model>
""")


def _write_tree_variant(models_dir, variant_idx, trunk_h, trunk_r, canopy_h, canopy_r):
    """Emit one reusable tree model. ``<include>``d many times in the world."""
    model_name = f"tree_generic_{variant_idx}"
    model_dir = os.path.join(models_dir, model_name)
    os.makedirs(model_dir, exist_ok=True)

    trunk_z = trunk_h / 2.0
    canopy_z = trunk_h + canopy_r * 0.6   # canopy sits slightly above trunk top
    # Trunk gets a box collision (conservative hull) so the rover can't drive
    # through tree trunks. Canopy is visual-only.
    sdf = f"""<?xml version='1.0'?>
<sdf version='1.10'>
  <model name='{model_name}'>
    <static>true</static>
    <link name='link'>
      <visual name='trunk'>
        <pose>0 0 {trunk_z:.3f} 0 0 0</pose>
        <geometry><cylinder><radius>{trunk_r:.3f}</radius><length>{trunk_h:.3f}</length></cylinder></geometry>
        <material>
          <ambient>0.30 0.20 0.10 1</ambient>
          <diffuse>0.30 0.20 0.10 1</diffuse>
        </material>
      </visual>
      <collision name='trunk'>
        <pose>0 0 {trunk_z:.3f} 0 0 0</pose>
        <geometry><cylinder><radius>{trunk_r:.3f}</radius><length>{trunk_h:.3f}</length></cylinder></geometry>
      </collision>
      <visual name='canopy'>
        <pose>0 0 {canopy_z:.3f} 0 0 0</pose>
        <geometry><sphere><radius>{canopy_r:.3f}</radius></sphere></geometry>
        <material>
          <ambient>0.12 0.38 0.12 1</ambient>
          <diffuse>0.15 0.45 0.15 1</diffuse>
          <specular>0.02 0.02 0.02 1</specular>
        </material>
      </visual>
    </link>
  </model>
</sdf>
"""
    with open(os.path.join(model_dir, 'model.sdf'), 'w') as f:
        f.write(sdf)
    _write_model_config(model_dir, model_name)
    return model_name


def _generate_tree_variants(models_dir):
    """Five reusable tree sizes (small shrub → large tree). Deterministic."""
    configs = [
        (3.0,  0.10, 1.5, 1.2),
        (5.0,  0.15, 2.0, 1.8),
        (7.0,  0.20, 2.5, 2.5),
        (9.0,  0.25, 3.0, 3.2),
        (12.0, 0.30, 3.5, 4.0),
    ]
    names = []
    for i, (th, tr, ch, cr) in enumerate(configs[:TREE_VARIANTS]):
        names.append(_write_tree_variant(models_dir, i, th, tr, ch, cr))
    return names


def _scatter_in_polygon(polygon, density, max_count, rng):
    """Poisson-ish point scatter inside a polygon at ``density`` points/m²."""
    minx, miny, maxx, maxy = polygon.bounds
    area = polygon.area
    target = min(max(int(area * density), 1), max_count)
    pts = []
    attempts = 0
    while len(pts) < target and attempts < target * 6:
        x = rng.uniform(minx, maxx)
        y = rng.uniform(miny, maxy)
        if polygon.contains(shapely.geometry.Point(x, y)):
            pts.append((x, y))
        attempts += 1
    return pts


def process_osm_trees_to_sdf(osm_filepath: str, models_dir: str, origin_wgs84: tuple,
                             elevation_sampler=None, cloud_mask=None,
                             seed: int = 1337) -> list:
    """Return a list of ``{model_name, pose_xy, pose_z}`` tree placements.

    Handles both point features (``natural=tree``) and polygon features
    (``natural=wood`` / ``landuse=forest``), scattering synthetic trees inside
    each forest polygon at ``FOREST_DENSITY`` up to ``MAX_FOREST_TREES``.
    """
    if not os.path.exists(osm_filepath):
        logger.info("No OSM foliage file; skipping trees stage.")
        return []

    logger.info(f"Processing OSM foliage from {osm_filepath}")
    os.makedirs(models_dir, exist_ok=True)
    variant_names = _generate_tree_variants(models_dir)
    rng = random.Random(seed)

    converter = CoordinateConverter(origin_wgs84)

    def project(x_lon, y_lat, z=None):
        gx, gy, _ = converter.wgs84_to_gazebo((y_lat, x_lon))
        return (gx, gy) if z is None else (gx, gy, z)

    placements = []
    forest_tree_budget = MAX_FOREST_TREES
    point_count = 0
    poly_count = 0
    cloud_skipped = 0

    with open(osm_filepath) as f:
        osm_data = json.load(f)

    def tree_is_cloudy(gx, gy):
        if cloud_mask is None:
            return False
        lat, lon = converter.gazebo_to_wgs84((gx, gy))
        return cloud_mask.is_cloudy(lat, lon)

    def add_tree(x, y):
        nonlocal cloud_skipped
        if tree_is_cloudy(x, y):
            cloud_skipped += 1
            return
        variant = variant_names[rng.randrange(TREE_VARIANTS)]
        z = float(elevation_sampler(x, y)) if elevation_sampler is not None else 0.0
        placements.append({'model_name': variant, 'pose_xy': (x, y), 'pose_z': z})

    for feature in osm_data['features']:
        geom = feature['geometry']
        gtype = geom['type']
        props = feature.get('properties', {}) or {}

        if gtype == 'Point':
            lon, lat = geom['coordinates'][:2]
            gx, gy, _ = converter.wgs84_to_gazebo((lat, lon))
            add_tree(gx, gy)
            point_count += 1

        elif gtype in ('Polygon', 'MultiPolygon'):
            # Only scatter inside forest-tagged polygons, not generic areas.
            is_forest = (
                props.get('natural') == 'wood' or
                props.get('landuse') == 'forest'
            )
            if not is_forest or forest_tree_budget <= 0:
                continue
            polygon_wgs84 = shapely.geometry.shape(geom)
            polygon_local = shapely.ops.transform(project, polygon_wgs84)
            if not polygon_local.is_valid or polygon_local.area <= 0:
                continue
            pts = _scatter_in_polygon(
                polygon_local, FOREST_DENSITY, forest_tree_budget, rng
            )
            forest_tree_budget -= len(pts)
            for x, y in pts:
                add_tree(x, y)
            poly_count += 1

    logger.info(
        f"OSM foliage processed: {len(placements)} trees "
        f"({point_count} mapped, {poly_count} forest polygons, "
        f"{cloud_skipped} cloud-masked) across {len(variant_names)} model variants"
    )
    return placements
