"""Turn OSM ``natural=tree`` points and ``natural=wood`` / ``landuse=forest``
polygons into Gazebo tree instances.

Each tree is a single static model (trunk cylinder + canopy sphere). We emit
one reusable ``tree_generic_<variant>`` model and place many ``<include>``
instances in the world — avoiding thousands of per-instance SDF files.
"""

import json
import os
import random

import shapely.affinity
import shapely.geometry
import shapely.ops

from terraforge.utils.coordinates import CoordinateConverter
from terraforge.utils.logging import logger

# Number of reusable tree variants (different heights / canopy radii) that
# will be generated once and referenced by each placement. Variants are sorted
# smallest -> largest in _generate_tree_variants; named subsets below pick
# index ranges so scrub uses small variants and forests use the full mix.
TREE_VARIANTS = 5
_VARIANT_SHRUB = (0, 1)        # small variants (~3-5 m) for scrub / heath / hedge
_VARIANT_MID = (1, 2, 3)       # mid variants (~5-9 m) for orchards / parks
_VARIANT_FOREST = (0, 1, 2, 3, 4)  # full mix for dense woods

# Per-class scatter density (trees per square meter) for polygon features.
# Densities are deliberately low for sparse cover (heath, scrub, vineyard)
# so the world doesn't drown in tree collision geometry, and the per-class
# variant pool controls canopy size.
_POLYGON_CLASSES = {
    ('natural', 'wood'):     {'density': 1 / 400.0,  'variants': _VARIANT_FOREST},
    ('landuse', 'forest'):   {'density': 1 / 400.0,  'variants': _VARIANT_FOREST},
    ('natural', 'scrub'):    {'density': 1 / 600.0,  'variants': _VARIANT_SHRUB},
    ('natural', 'heath'):    {'density': 1 / 800.0,  'variants': _VARIANT_SHRUB},
    ('landuse', 'orchard'):  {'density': 1 / 300.0,  'variants': _VARIANT_MID},
    ('landuse', 'vineyard'): {'density': 1 / 800.0,  'variants': _VARIANT_SHRUB},
    ('leisure', 'park'):     {'density': 1 / 1500.0, 'variants': _VARIANT_MID},
    ('leisure', 'garden'):   {'density': 1 / 400.0,  'variants': _VARIANT_MID},
}

# Per-meter density for LineString features like natural=tree_row / hedge.
# A dense hedgerow is ~one shrub every 2 m.
_LINESTRING_DENSITY = 1 / 2.0

# Hard cap on scattered trees per world to keep Gazebo sane. gz-transport v13
# has a thread-safety bug around getenv() that segfaults the GUI when scene
# updates fire too fast during load; keeping total instances modest helps.
# Bumped from 200 -> 1500 now that scrub / orchard / park classes contribute
# (rural sites often have more scrub than forest) and variants span shrub
# -> tree so the collision load per instance scales with size.
MAX_FOREST_TREES = 1500


def _write_model_config(model_dir, model_name):
    with open(os.path.join(model_dir, 'model.config'), 'w') as f:
        f.write(f"""<?xml version='1.0'?>
<model>
  <name>{model_name}</name>
  <version>1.0</version>
  <sdf version='1.10'>model.sdf</sdf>
  <description>Generated by TerraForge.</description>
</model>
""")


def _write_tree_variant(models_dir, variant_idx, trunk_h, trunk_r, canopy_h, canopy_r):
    """Emit one reusable tree model. ``<include>``d many times in the world."""
    model_name = f"tree_generic_{variant_idx}"
    model_dir = os.path.join(models_dir, model_name)
    os.makedirs(model_dir, exist_ok=True)

    trunk_z = trunk_h / 2.0
    canopy_z = trunk_h + canopy_r * 0.6   # canopy sits slightly above trunk top
    # Trunk gets a box collision (conservative hull) so the rover can't drive
    # through tree trunks. Canopy is visual-only.
    sdf = f"""<?xml version='1.0'?>
<sdf version='1.10'>
  <model name='{model_name}'>
    <static>true</static>
    <link name='link'>
      <visual name='trunk'>
        <pose>0 0 {trunk_z:.3f} 0 0 0</pose>
        <geometry><cylinder><radius>{trunk_r:.3f}</radius><length>{trunk_h:.3f}</length></cylinder></geometry>
        <material>
          <ambient>0.30 0.20 0.10 1</ambient>
          <diffuse>0.30 0.20 0.10 1</diffuse>
        </material>
      </visual>
      <collision name='trunk'>
        <pose>0 0 {trunk_z:.3f} 0 0 0</pose>
        <geometry><cylinder><radius>{trunk_r:.3f}</radius><length>{trunk_h:.3f}</length></cylinder></geometry>
      </collision>
      <visual name='canopy'>
        <pose>0 0 {canopy_z:.3f} 0 0 0</pose>
        <geometry><sphere><radius>{canopy_r:.3f}</radius></sphere></geometry>
        <material>
          <ambient>0.12 0.38 0.12 1</ambient>
          <diffuse>0.15 0.45 0.15 1</diffuse>
          <specular>0.02 0.02 0.02 1</specular>
        </material>
      </visual>
    </link>
  </model>
</sdf>
"""
    with open(os.path.join(model_dir, 'model.sdf'), 'w') as f:
        f.write(sdf)
    _write_model_config(model_dir, model_name)
    return model_name


def _generate_tree_variants(models_dir):
    """Five reusable tree sizes (small shrub → large tree). Deterministic."""
    configs = [
        (3.0,  0.10, 1.5, 1.2),
        (5.0,  0.15, 2.0, 1.8),
        (7.0,  0.20, 2.5, 2.5),
        (9.0,  0.25, 3.0, 3.2),
        (12.0, 0.30, 3.5, 4.0),
    ]
    names = []
    for i, (th, tr, ch, cr) in enumerate(configs[:TREE_VARIANTS]):
        names.append(_write_tree_variant(models_dir, i, th, tr, ch, cr))
    return names


def _scatter_in_polygon(polygon, density, max_count, rng):
    """Poisson-ish point scatter inside a polygon at ``density`` points/m²."""
    minx, miny, maxx, maxy = polygon.bounds
    area = polygon.area
    target = min(max(int(area * density), 1), max_count)
    pts = []
    attempts = 0
    while len(pts) < target and attempts < target * 6:
        x = rng.uniform(minx, maxx)
        y = rng.uniform(miny, maxy)
        if polygon.contains(shapely.geometry.Point(x, y)):
            pts.append((x, y))
        attempts += 1
    return pts


def process_osm_trees_to_sdf(osm_filepath: str, models_dir: str, origin_wgs84: tuple,
                             elevation_sampler=None, cloud_mask=None,
                             world_half_extent_m: float = None,
                             seed: int = 1337) -> list:
    """Return a list of ``{model_name, pose_xy, pose_z}`` tree placements.

    Handles both point features (``natural=tree``) and polygon features
    (``natural=wood`` / ``landuse=forest``), scattering synthetic trees inside
    each forest polygon at ``FOREST_DENSITY`` up to ``MAX_FOREST_TREES``.
    """
    if not os.path.exists(osm_filepath):
        logger.info("No OSM foliage file; skipping trees stage.")
        return []

    logger.info(f"Processing OSM foliage from {osm_filepath}")
    os.makedirs(models_dir, exist_ok=True)
    variant_names = _generate_tree_variants(models_dir)
    rng = random.Random(seed)

    converter = CoordinateConverter(origin_wgs84)

    def project(x_lon, y_lat, z=None):
        gx, gy, _ = converter.wgs84_to_gazebo((y_lat, x_lon))
        return (gx, gy) if z is None else (gx, gy, z)

    placements = []
    forest_tree_budget = MAX_FOREST_TREES
    point_count = 0
    poly_count = 0
    cloud_skipped = 0
    out_of_world_skipped = 0

    # Clip forest polygons to this square so trees from a large natural=wood
    # feature don't scatter far outside the terrain's extent. Point trees
    # (natural=tree) get a separate per-point bounds check.
    world_box = None
    if world_half_extent_m is not None and world_half_extent_m > 0:
        world_box = shapely.geometry.box(
            -world_half_extent_m, -world_half_extent_m,
            world_half_extent_m, world_half_extent_m,
        )

    with open(osm_filepath) as f:
        osm_data = json.load(f)

    def in_world(x, y):
        if world_half_extent_m is None:
            return True
        return (-world_half_extent_m <= x <= world_half_extent_m and
                -world_half_extent_m <= y <= world_half_extent_m)

    def tree_is_cloudy(gx, gy):
        if cloud_mask is None:
            return False
        lat, lon = converter.gazebo_to_wgs84((gx, gy))
        return cloud_mask.is_cloudy(lat, lon)

    def add_tree(x, y, variant_pool=None):
        nonlocal cloud_skipped, out_of_world_skipped
        if not in_world(x, y):
            out_of_world_skipped += 1
            return
        if tree_is_cloudy(x, y):
            cloud_skipped += 1
            return
        pool = variant_pool if variant_pool is not None else tuple(range(TREE_VARIANTS))
        variant = variant_names[rng.choice(pool)]
        z = float(elevation_sampler(x, y)) if elevation_sampler is not None else 0.0
        placements.append({'model_name': variant, 'pose_xy': (x, y), 'pose_z': z})

    def _classify_polygon(props):
        """Return the _POLYGON_CLASSES entry matching this feature's tags,
        or None if the polygon isn't a recognized foliage class."""
        for (key, value), cfg in _POLYGON_CLASSES.items():
            if props.get(key) == value:
                return cfg
        return None

    line_count = 0
    for feature in osm_data['features']:
        geom = feature['geometry']
        gtype = geom['type']
        props = feature.get('properties', {}) or {}

        if gtype == 'Point':
            lon, lat = geom['coordinates'][:2]
            gx, gy, _ = converter.wgs84_to_gazebo((lat, lon))
            # Individual OSM trees are usually medium-sized; skip the
            # largest-forest and smallest-shrub variants to keep them
            # looking like single mature trees rather than a 12 m monster.
            add_tree(gx, gy, variant_pool=_VARIANT_MID)
            point_count += 1

        elif gtype == 'LineString':
            # Hedgerows / tree_row / tree lines. Scatter shrub-sized variants
            # along the line at _LINESTRING_DENSITY. Treat MultiLineString via
            # iteration over parts if we ever see them.
            if forest_tree_budget <= 0:
                continue
            line_wgs84 = shapely.geometry.shape(geom)
            line_local = shapely.ops.transform(project, line_wgs84)
            if world_box is not None:
                line_local = line_local.intersection(world_box)
                if line_local.is_empty:
                    continue
            length = line_local.length
            target = min(int(length * _LINESTRING_DENSITY),
                         forest_tree_budget)
            for i in range(target):
                t = (i + 0.5) / max(target, 1)
                pt = line_local.interpolate(t, normalized=True)
                add_tree(pt.x, pt.y, variant_pool=_VARIANT_SHRUB)
            forest_tree_budget -= target
            line_count += 1

        elif gtype in ('Polygon', 'MultiPolygon'):
            cfg = _classify_polygon(props)
            if cfg is None or forest_tree_budget <= 0:
                continue
            polygon_wgs84 = shapely.geometry.shape(geom)
            polygon_local = shapely.ops.transform(project, polygon_wgs84)
            if not polygon_local.is_valid or polygon_local.area <= 0:
                continue
            # OSM returns the feature's full geometry (which can span km beyond
            # the user's bbox). Clip to the world square so scattered trees
            # can't land outside the terrain mesh.
            if world_box is not None:
                polygon_local = polygon_local.intersection(world_box)
                if polygon_local.is_empty or polygon_local.area <= 0:
                    continue
            pts = _scatter_in_polygon(
                polygon_local, cfg['density'], forest_tree_budget, rng
            )
            forest_tree_budget -= len(pts)
            for x, y in pts:
                add_tree(x, y, variant_pool=cfg['variants'])
            poly_count += 1

    logger.info(
        f"OSM foliage processed: {len(placements)} trees "
        f"({point_count} mapped points, {line_count} hedgerows, "
        f"{poly_count} vegetated polygons, "
        f"{cloud_skipped} cloud-masked, {out_of_world_skipped} outside-world) "
        f"across {len(variant_names)} model variants"
    )
    return placements
